service: serverless-example
frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev

environment:
  DB_HOST: ${env:DB_HOST}
  DB_PORT: ${env:DB_PORT}
  DB_NAME: ${env:DB_NAME}
  DB_USERNAME: ${env:DB_USERNAME}
  DB_PASSWORD: ${env:DB_PASSWORD}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
