service: cart-service

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          cors: true
          method: ANY
          path: /
      - http:
          cors: true
          method: ANY
          path: '{proxy+}'