branch-defaults:
  main:
    environment: lemtoup-cart-api-dev
environment-defaults:
  lemtoup-cart-api-dev:
    branch: null
    repository: null
global:
  application_name: lemtoup-cart-api
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
